version: '3.8'

services:

  ### 🐳 Docker Registry v2 ###
  registry:
    image: registry:2
    container_name: docker-registry
    restart: always
    environment:
      REGISTRY_CONFIG_PATH: /etc/docker/registry/config.yml
    ports:
      - "5000:5000"
    volumes:
      - registry_data:/var/lib/registry
      - ./registry/auth:/auth
      - ./registry/config.yml:/etc/docker/registry/config.yml
    networks:
      - registry-net

  ### 🌐 Nginx CORS Proxy ###
  nginx:
    image: nginx:alpine
    container_name: registry-nginx
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - registry-net
    depends_on:
      - registry

volumes:
  registry_data:

networks:
  registry-net:
    driver: bridge
