name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Enable corepack
        run: corepack enable

      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install dependencies (pnpm)
        run: pnpm install --frozen-lockfile

      - name: Run lint
        run: pnpm lint --max-warnings=0

      - name: Run tests
        env:
          CI: true
        run: pnpm test -- --run

      - name: Typecheck
        run: pnpm exec tsc --noEmit

      - name: Build (optional)
        run: pnpm build || true
